### ISSUE TITLE
Not Able to start Pico Server on python 3.5

### ISSUE THREAD

**Issue by Anarach** [fergalwalsh/pico#13]
I installed Pico on my Machine with Python 3.5 and when I try to run the Pico Server using.

Python -m pico,server  

I get the following message.

`
C:\Windows\system32>python -m pico.server
Traceback (most recent call last):
  File "C:\python35\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "C:\python35\lib\runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\python35\pico\server.py", line 393
    except OSError, e:
                  ^
SyntaxError: invalid syntax

C:\Windows\system32>`

**Comment by aldenweaver** [comment]
I am having the same issue

**Comment by aeroaks** [comment]
I installed `pico` in my virtualenv in Windows using Python 3.5. I used the `examples` to check and it works properly!

**Comment by fergalwalsh** [comment]
Since version `2.0.0` pico is Python 3.5+ compatible. Closing this issue as it is no longer relevant.
